language: julia

os:
  - linux

julia:
  - 1.0


notifications:
  email: false

script:
  - julia -E 'string("script folder ", pwd())'

jobs:
  include:
    - stage: "TestAndDocs"
      julia: 1.0
      os: linux
      script:
        - julia -E 'string("Build folder ", pwd())'
        - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/pszufe/SimpleHypergraphs.jl")); Pkg.instantiate(); Pkg.build("HypergraphsYelp"); Pkg.test("HypergraphsYelp"; coverage=true)'
        - ls */* 
        - julia -E 'string("Docs folder ", pwd())'
        - julia --project=docs/ -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/pszufe/SimpleHypergraphs.jl")); Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'        
        - julia --project=docs/ docs/make.jl        
        - ls */* 

  
after_success:
  - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/pszufe/SimpleHypergraphs.jl")); cd(Pkg.dir("HypergraphsYelp")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
