language: julia

os:
  - osx
  - linux

julia:
  - 1.0


notifications:
  email: false

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("HypergraphsYelp")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
